"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vzi41+%m_l*41ki5*u7^upd-)_w90y)16avq)^8)fc=ty32a+#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]



# Application definition

INSTALLED_APPS = [
    'apps.voice_services.apps.VoiceServicesConfig',
    'apps.ussd.apps.USSDConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'apps.events',
    'apps.accounts.apps.AccountsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration


# Transactional email: Brevo SMTP
#
# In local development, use console email until SMTP credentials
# are configured in backend/.env.
#
# Never place SMTP credentials directly in this file.

BREVO_SMTP_READY = all(
    os.getenv(name)
    for name in (
        "EMAIL_HOST_USER",
        "EMAIL_HOST_PASSWORD",
        "DEFAULT_FROM_EMAIL",
    )
)

if BREVO_SMTP_READY:
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
            "OPTIONS": {
                "host": os.getenv(
                    "EMAIL_HOST",
                    "smtp-relay.brevo.com",
                ),
                "port": int(os.getenv("EMAIL_PORT", "587")),
                "username": os.environ["EMAIL_HOST_USER"],
                "password": os.environ["EMAIL_HOST_PASSWORD"],
                "use_tls": True,
                "timeout": 20,
            },
        },
    }
else:
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.console.EmailBackend",
        },
    }

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "Tuviora <noreply@tuviora.local>",
)



# Public frontend URL used to generate verification links.
FRONTEND_BASE_URL = "http://localhost:5173"

# Sender displayed in development emails.


# SMS is disabled unless explicitly enabled.
SMS_ENABLED = os.getenv(
    "SMS_ENABLED", "false"
).strip().lower() == "true"

# Africa's Talking SMS configuration
AFRICASTALKING_USERNAME = os.getenv(
    "AFRICASTALKING_USERNAME", ""
)
AFRICASTALKING_API_KEY = os.getenv(
    "AFRICASTALKING_API_KEY", ""
)
AFRICASTALKING_SENDER_ID = os.getenv(
    "AFRICASTALKING_SENDER_ID", ""
)

# MarzPay payment collection (https://wallet.wearemarz.com)
MARZPAY_BASE_URL = os.getenv(
    "MARZPAY_BASE_URL", "https://wallet.wearemarz.com/api/v1"
).strip()
MARZPAY_API_KEY = os.getenv("MARZPAY_API_KEY", "").strip()
MARZPAY_API_SECRET = os.getenv("MARZPAY_API_SECRET", "").strip()
MARZPAY_WEBHOOK_SECRET = os.getenv(
    "MARZPAY_WEBHOOK_SECRET", ""
).strip()
MARZPAY_CALLBACK_URL = os.getenv("MARZPAY_CALLBACK_URL", "").strip()
MARZPAY_DEFAULT_COUNTRY = os.getenv(
    "MARZPAY_DEFAULT_COUNTRY", "UG"
).strip()

# Africa's Talking Voice
AT_VOICE_NUMBER = os.getenv("AT_VOICE_NUMBER", "").strip()
AT_VOICE_CALLBACK_URL = os.getenv(
    "AT_VOICE_CALLBACK_URL", ""
).strip()

# Shared cache for production conference security.
# Local development keeps Django's default in-memory cache.
REDIS_URL = os.getenv("REDIS_URL", "").strip()

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "TIMEOUT": 900,
        }
    }


# Private event conferences
VOICE_CONFERENCE_ENABLED = (
    os.getenv("VOICE_CONFERENCE_ENABLED", "false").lower()
    == "true"
)

VOICE_CONFERENCE_MAX_PARTICIPANTS = int(
    os.getenv("VOICE_CONFERENCE_MAX_PARTICIPANTS", "20")
)
