# Generated by Django 6.1.1 on 2026-09-23 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeedbackAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes', models.JSONField(default=list)),
                ('concerns_summary', models.TextField(blank=True)),
                ('suggested_improvements', models.JSONField(default=list)),
                ('analysis_type', models.CharField(default='AI-generated analysis', max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback_analysis', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
