# Generated by Django 6.1.1 on 2026-09-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_aifeedbackanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timezone_name',
            field=models.CharField(default='Africa/Kampala', max_length=64),
        ),
    ]
