# Generated by Django 6.1.1 on 2026-09-25 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_feedback_comment_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('event', 'attendee'), name='unique_event_attendee_feedback'),
        ),
    ]
