# Generated by Django 6.1.1 on 2026-09-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_services', '0002_conferenceaccesscode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingVoiceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number', 'expires_at'], name='voice_servi_phone_n_ebea9c_idx')],
            },
        ),
    ]
