import TuvioraLogo from '../components/TuvioraLogo'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Accessibility, ArrowRight, CheckCircle2, ClipboardCheck, CreditCard, Menu, MessageSquareText, RadioTower, ScanLine, X } from 'lucide-react'

const img = (name) => `/images/${name}`
const links = [ ['Why Tuviora','#why'], ['Features','#features'], ['How it works','#how'], ['Event types','#events'] ]
const features = [
  { icon: ClipboardCheck, image:'tuviora-event-readiness.png', title:'Prepare with confidence', text:'Organize resources, assign responsibilities and keep event readiness in view.' },
  { icon: ScanLine, image:'tuviora-registration-checkin.png', title:'Welcome every guest', text:'Connect registration, payment status and verified attendance in one place.' },
  { icon: RadioTower, image:'tuviora-live-event-coordination.png', title:'Respond together', text:'Coordinate teams, communicate changes and help affected attendees stay informed.' },
]
const steps = [
  ['01','Plan','Create your event and prepare your venue, schedule and team.'],
  ['02','Welcome','Manage registration, payments and attendance with inclusive options.'],
  ['03','Coordinate','Share relevant updates and address unexpected problems.'],
  ['04','Improve','Act on attendee feedback and carry lessons into your next event.'],
]

function Header() {
  const [open, setOpen] = useState(false)
  return <header className="sticky top-0 z-50 border-b border-[#E5EAE1] bg-white/95 shadow-[0_4px_24px_rgba(26,63,34,0.04)] backdrop-blur-xl">
    <nav aria-label="Main navigation" className="tuviora-container flex min-h-20 items-center justify-between gap-5 py-3">
      <TuvioraLogo />
      <div className="hidden items-center gap-6 xl:gap-8 lg:flex">{links.map(([name,href])=><a key={name} href={href} className="text-[15px] font-semibold text-[#405642] transition-colors hover:text-[#58761B]">{name}</a>)}</div>
      <Link to="/operations" className="hidden text-[15px] font-semibold text-[#1A3F22] transition-colors hover:text-[#58761B] xl:inline-flex">Organizer workspace</Link><Link className="tuviora-button-primary hidden whitespace-nowrap text-[15px] lg:inline-flex" to="/events">Explore events <ArrowRight size={17}/></Link>
      <button type="button" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} onClick={()=>setOpen(!open)} className="rounded-lg border border-[#E1E8DC] p-2.5 text-[#1A3F22] transition-colors hover:bg-[#F3F6EE] lg:hidden">{open?<X/>:<Menu/>}</button>
    </nav>
    {open && <div className="border-t border-[#E5EAE1] px-5 pb-5 lg:hidden"><div className="mx-auto flex max-w-7xl flex-col gap-1">{links.map(([name,href])=><a key={name} href={href} onClick={()=>setOpen(false)} className="rounded-lg p-3 font-medium hover:bg-[#F3F6EE]">{name}</a>)}<Link to="/events" onClick={() => setOpen(false)} className="mt-2 rounded-lg bg-[#1A3F22] p-3 text-center font-semibold text-white">Explore events</Link><Link to="/operations" onClick={() => setOpen(false)} className="rounded-lg border border-[#B9C9B3] p-3 text-center font-semibold text-[#1A3F22]">Organizer workspace</Link></div></div>}
  </header>
}

function Hero() { return <section className="relative overflow-hidden bg-[#F8F9F5]"><div className="tuviora-container relative grid items-center gap-9 py-10 sm:py-14 lg:min-h-[650px] lg:grid-cols-2 lg:gap-16 lg:py-24">
  <div className="tuviora-hero-copy"><p className="mb-5 inline-flex rounded-full border border-[#DCE8D5] bg-white px-4 py-2 text-xs font-bold uppercase tracking-[.13em] text-[#58761B]">One connected event experience</p>
    <h1 className="max-w-2xl text-[clamp(2.7rem,5vw,4.9rem)] font-bold leading-[1.07] tracking-[-0.045em] text-[#1A3F22]">Every event deserves to run beautifully.</h1>
    <p className="mt-5 max-w-xl text-base leading-7 text-[#526052] sm:mt-7 sm:text-lg sm:leading-8">From your first plan to your final guest, Tuviora brings planning, payments, attendance and real-time coordination together in an inclusive platform.</p>
    <div className="mt-7 flex flex-wrap gap-3 sm:mt-9"><Link className="tuviora-button-primary" to="/events">Explore events <ArrowRight size={18}/></Link><a className="tuviora-button-secondary" href="#features">Explore features</a></div>
    <div className="mt-8 flex flex-wrap gap-x-4 gap-y-2 border-t border-[#DFE6D9] pt-5 text-sm font-medium text-[#405642] sm:mt-10 sm:pt-7">{['Every event type','Inclusive by design','Connected operations'].map(t=><span key={t} className="inline-flex items-center gap-2"><CheckCircle2 size={17} className="text-[#58761B]"/>{t}</span>)}</div>
  </div>
  <div className="tuviora-hero-image relative"><img src={img('tuviora-event-planning.png')} alt="Event planning and organization" className="h-[280px] w-full rounded-[24px] object-cover shadow-[0_24px_65px_rgba(26,63,34,0.16)] sm:h-[500px] sm:rounded-[28px]"/><div className="relative -mt-10 ml-5 max-w-xs rounded-xl border border-border-soft bg-white p-5 shadow-lg sm:-ml-6"><p className="text-xs font-bold uppercase tracking-widest text-[#58761B]">Our approach</p><p className="mt-2 text-lg font-bold text-[#1A3F22]">Plan. Connect. Adapt.</p><p className="mt-2 text-sm leading-6 text-[#5C695B]">Clarity for organizers. A voice for every attendee.</p></div></div>
</div></section> }

function SectionTitle({eyebrow, title, description}) { return <div className="mb-11 max-w-2xl"><p className="mb-3 text-xs font-bold uppercase tracking-[.17em] text-[#58761B]">{eyebrow}</p><h2 className="text-3xl font-bold leading-tight tracking-tight text-[#1A3F22] sm:text-4xl">{title}</h2>{description && <p className="mt-5 text-lg leading-8 text-[#526052]">{description}</p>}</div> }

function Why() { return <section id="why" className="scroll-mt-24 bg-white py-20 lg:py-24"><div className="tuviora-container grid items-center gap-12 lg:grid-cols-2 lg:gap-16"><div><SectionTitle eyebrow="Why Tuviora" title="When plans change, everyone should stay connected." description="An event brings people, places, payments and schedules together. When circumstances change, scattered tools make coordination more difficult."/><div className="space-y-4">{['See what is ready and what needs attention.','Connect registration, payments and verified attendance.','Coordinate responses and listen to attendee feedback.'].map(item=><p key={item} className="flex items-start gap-3 leading-7 text-[#425043]"><CheckCircle2 className="mt-1 shrink-0 text-[#58761B]" size={20}/>{item}</p>)}</div></div><img src={img('tuviora-live-event-coordination.png')} alt="Team coordinating a live event" loading="lazy" className="h-[380px] w-full rounded-2xl object-cover lg:h-[480px]"/></div></section> }

function Features() {return <section id="features" className="scroll-mt-24 bg-[#F8F9F5] py-20 lg:py-24"><div className="tuviora-container"><SectionTitle eyebrow="The platform" title="Everything connected. Nothing complicated." description="The tools your event needs, organized around the moments that matter most."/><div className="grid gap-6 lg:grid-cols-3">{features.map(({icon:Icon,image,title,text})=><article key={title} className="tuviora-card tuviora-surface-card group overflow-hidden"><img src={img(image)} alt={title} loading="lazy" className="h-60 w-full object-cover transition-transform duration-500 group-hover:scale-[1.04]"/><div className="p-7"><div className="mb-5 inline-flex rounded-xl bg-[#EEF3E9] p-3 text-[#58761B]"><Icon size={23}/></div><h3 className="text-xl font-bold text-[#1A3F22]">{title}</h3><p className="mt-3 leading-7 text-[#576657]">{text}</p></div></article>)}</div><div className="mt-6 grid gap-4 md:grid-cols-3">{[[CreditCard,'Payments','Register and pay with supported methods.'],[MessageSquareText,'Attendee feedback','Hear and act on what participants experience.'],[Accessibility,'Accessible participation','Support varied communication and assistance needs.']].map(([Icon,title,text])=><div key={title} className="tuviora-card tuviora-surface-card flex gap-4 p-6"><Icon className="shrink-0 text-[#58761B]"/><div><h3 className="font-bold text-[#1A3F22]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#576657]">{text}</p></div></div>)}</div></div></section>}

function How() { return <section id="how" className="scroll-mt-24 bg-white py-20 lg:py-24"><div className="tuviora-container"><SectionTitle eyebrow="How it works" title="Simpler from beginning to end." description="Four connected stages make the event journey manageable."/><div className="grid gap-7 sm:grid-cols-2 lg:grid-cols-4">{steps.map(([number,title,text])=><article key={number} className="border-t-2 border-[#D8E4D1] pt-6 transition-colors duration-200 hover:border-[#58761B]"><span className="text-sm font-bold text-[#905A01]">{number}</span><h3 className="mt-5 text-2xl font-bold text-[#1A3F22]">{title}</h3><p className="mt-4 leading-7 text-[#586858]">{text}</p></article>)}</div></div></section> }

function EventTypes() {return <section id="events" className="scroll-mt-24 bg-[#F8F9F5] py-20 lg:py-24"><div className="tuviora-container"><SectionTitle eyebrow="For every occasion" title="Different events. One connected experience." description="Flexible enough for celebrations, conferences, festivals and community gatherings."/><div className="grid gap-6 md:grid-cols-2">{[['tuviora-wedding-management.png','Weddings and celebrations'],['tuviora-community-fundraising.png','Community gatherings and fundraisers']].map(([image,title])=><div key={image} className="group relative overflow-hidden rounded-2xl"><img src={img(image)} alt={title} loading="lazy" className="h-80 w-full object-cover transition-transform duration-500 group-hover:scale-[1.04]"/><div className="absolute inset-0 bg-gradient-to-t from-[#102B17]/80 via-transparent to-transparent"/><h3 className="absolute bottom-7 left-7 right-7 text-2xl font-bold text-white">{title}</h3></div>)}</div><p className="mt-7 text-center text-sm font-medium text-[#58761B]">Also designed for corporate, academic, cultural, virtual and hybrid events.</p></div></section> }

function Bottom() {return <><section className="bg-white py-20"><div className="tuviora-container grid items-center gap-10 lg:grid-cols-2"><div><Accessibility className="mb-5 text-[#58761B]" size={34}/><SectionTitle eyebrow="Inclusive by design" title="Every attendee deserves to participate." description="Tuviora is being designed for accessible web interactions, SMS, USSD, Voice and staff-assisted experiences, with optional assistance preferences and clear communications."/></div><div className="grid gap-4 sm:grid-cols-2">{[['Relevant updates','Help the right people receive important changes.'],['Flexible check-in','Support QR, reference and staff-assisted methods.'],['Assistance requests','Make it simple to ask the event team for help.'],['A voice for everyone','Gather feedback and respond to reported issues.']].map(([title,text])=><div key={title} className="rounded-xl border border-border-soft bg-[#F8F9F5] p-6"><h3 className="font-bold text-[#1A3F22]">{title}</h3><p className="mt-3 text-sm leading-7 text-[#586858]">{text}</p></div>)}</div></div></section><section className="bg-[#1A3F22] px-5 py-20 text-center text-white"><div className="mx-auto max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.17em] text-[#E9B64E]">Every event. Every voice. In sync.</p><h2 className="mt-5 text-4xl font-bold leading-tight sm:text-5xl">Bring every event together.</h2><p className="mt-5 text-lg leading-8 text-white/80">One connected experience for organizing, coordinating and learning.</p><Link className="mt-8 inline-flex items-center gap-2 rounded-lg bg-[#D99201] px-7 py-3.5 font-bold text-[#1A3F22] hover:bg-[#E9AB30]" to="/events">Explore events <ArrowRight size={19}/></Link></div></section><footer className="bg-[#102A17] py-10 text-white"><div className="tuviora-container flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><TuvioraLogo dark imageClassName="h-9 w-auto max-w-[145px]" /><p className="mt-2 text-sm text-white/70">Every event. Every voice. In sync.</p></div><div className="text-sm text-white/70">© {new Date().getFullYear()} Tuviora · Built by <a href="https://github.com/ImpactStack-Labs/tuviora" target="_blank" rel="noreferrer" className="underline underline-offset-4 hover:text-white">ImpactStack Labs</a></div></div></footer></>}

export default function PublicHome(){return <><Header/><main><Hero/><Why/><Features/><How/><EventTypes/><Bottom/></main></>}
